// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoTakaTaka.BD.Datos;

#nullable disable

namespace ProyectoTakaTaka.BD.Migrations
{
    [DbContext(typeof(MiDbContext))]
    [Migration("20251017053733_Inicio1")]
    partial class Inicio1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProyectoTakaTaka.BD.Datos.Entity.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EstadoRegistro")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("ProyectoTakaTaka.BD.Datos.Entity.Combo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EstadoRegistro")
                        .HasColumnType("int");

                    b.Property<string>("NomCombo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Precio")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Combos");
                });

            modelBuilder.Entity("ProyectoTakaTaka.BD.Datos.Entity.Cumpleanero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<int>("EstadoRegistro")
                        .HasColumnType("int");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Cumpleaneros");
                });

            modelBuilder.Entity("ProyectoTakaTaka.BD.Datos.Entity.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EstadoRegistro")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("ProyectoTakaTaka.BD.Datos.Entity.Evento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<int>("ComboId")
                        .HasColumnType("int");

                    b.Property<int>("CumplaneroId")
                        .HasColumnType("int");

                    b.Property<int?>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<int>("EstadoRegistro")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<int>("HorarioId")
                        .HasColumnType("int");

                    b.Property<string>("Tematica")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ComboId");

                    b.HasIndex("CumplaneroId");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("HorarioId");

                    b.ToTable("Eventos");
                });

            modelBuilder.Entity("ProyectoTakaTaka.BD.Datos.Entity.EventoOpcional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EstadoRegistro")
                        .HasColumnType("int");

                    b.Property<int>("EventoId")
                        .HasColumnType("int");

                    b.Property<int>("OpcionalId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventoId");

                    b.HasIndex("OpcionalId");

                    b.ToTable("EventosOpcionales");
                });

            modelBuilder.Entity("ProyectoTakaTaka.BD.Datos.Entity.Horario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Disponible")
                        .HasColumnType("bit");

                    b.Property<int>("EstadoRegistro")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("HFin")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("HInicio")
                        .HasColumnType("time");

                    b.Property<bool>("MediaHoraExtra")
                        .HasColumnType("bit");

                    b.Property<int?>("MesId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MesId");

                    b.ToTable("Horarios");
                });

            modelBuilder.Entity("ProyectoTakaTaka.BD.Datos.Entity.Mes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Año")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EstadoRegistro")
                        .HasColumnType("int");

                    b.Property<string>("MesHabilitado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Meses");
                });

            modelBuilder.Entity("ProyectoTakaTaka.BD.Datos.Entity.Opcional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EstadoRegistro")
                        .HasColumnType("int");

                    b.Property<string>("NomOpcional")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Precio")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Opcionales");
                });

            modelBuilder.Entity("ProyectoTakaTaka.BD.Datos.Entity.Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EstadoPago")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EstadoRegistro")
                        .HasColumnType("int");

                    b.Property<int>("EventoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("datetime2");

                    b.Property<string>("Metodo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Monto")
                        .HasMaxLength(100)
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("EventoId");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("ProyectoTakaTaka.BD.Datos.Entity.Cumpleanero", b =>
                {
                    b.HasOne("ProyectoTakaTaka.BD.Datos.Entity.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("ProyectoTakaTaka.BD.Datos.Entity.Evento", b =>
                {
                    b.HasOne("ProyectoTakaTaka.BD.Datos.Entity.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProyectoTakaTaka.BD.Datos.Entity.Combo", "Combo")
                        .WithMany()
                        .HasForeignKey("ComboId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProyectoTakaTaka.BD.Datos.Entity.Cumpleanero", "Cumplanero")
                        .WithMany()
                        .HasForeignKey("CumplaneroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProyectoTakaTaka.BD.Datos.Entity.Empleado", "Empleado")
                        .WithMany("Eventos")
                        .HasForeignKey("EmpleadoId");

                    b.HasOne("ProyectoTakaTaka.BD.Datos.Entity.Horario", "Horario")
                        .WithMany("Eventos")
                        .HasForeignKey("HorarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Combo");

                    b.Navigation("Cumplanero");

                    b.Navigation("Empleado");

                    b.Navigation("Horario");
                });

            modelBuilder.Entity("ProyectoTakaTaka.BD.Datos.Entity.EventoOpcional", b =>
                {
                    b.HasOne("ProyectoTakaTaka.BD.Datos.Entity.Evento", "Evento")
                        .WithMany("EventoOpcionales")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProyectoTakaTaka.BD.Datos.Entity.Opcional", "Opcional")
                        .WithMany("EventoOpcionales")
                        .HasForeignKey("OpcionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Evento");

                    b.Navigation("Opcional");
                });

            modelBuilder.Entity("ProyectoTakaTaka.BD.Datos.Entity.Horario", b =>
                {
                    b.HasOne("ProyectoTakaTaka.BD.Datos.Entity.Mes", null)
                        .WithMany("Horarios")
                        .HasForeignKey("MesId");
                });

            modelBuilder.Entity("ProyectoTakaTaka.BD.Datos.Entity.Pago", b =>
                {
                    b.HasOne("ProyectoTakaTaka.BD.Datos.Entity.Evento", "Evento")
                        .WithMany("Pagos")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("ProyectoTakaTaka.BD.Datos.Entity.Empleado", b =>
                {
                    b.Navigation("Eventos");
                });

            modelBuilder.Entity("ProyectoTakaTaka.BD.Datos.Entity.Evento", b =>
                {
                    b.Navigation("EventoOpcionales");

                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("ProyectoTakaTaka.BD.Datos.Entity.Horario", b =>
                {
                    b.Navigation("Eventos");
                });

            modelBuilder.Entity("ProyectoTakaTaka.BD.Datos.Entity.Mes", b =>
                {
                    b.Navigation("Horarios");
                });

            modelBuilder.Entity("ProyectoTakaTaka.BD.Datos.Entity.Opcional", b =>
                {
                    b.Navigation("EventoOpcionales");
                });
#pragma warning restore 612, 618
        }
    }
}
